## 数据库
spring:
  datasource:
    druid:
      initial-size: 5
      max-active: 25
      validation-query: select 'x'
      filters: stat,wall
      web-stat-filter:
        enabled: true
        url-pattern: "*"
        exclusions: "*.css,*.js,*.gif,*.jpg,*.png,*.ico,/druid/*"
      stat-view-servlet:
        login-username: cd
        login-password: cd
        enabled: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.66:3306/yipandian?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: "ElTYgFNDMe7gXESg"
  ## redis
  redis:
    database: 4
    host: 192.168.2.66
    port: 6379
    password: "p855PYHN3DVeJKUl"
    testOnBorrow: false
    #连接池
    jedis:
      pool:
        #最大连接个数
        max-active: 100
        #等待时间
        max-wait: 3000
        #最大空闲
        max-idle: 20
        #初始化最小
        min-idle: 5
    timeout: 3000


cloudmessage:
  name-server: 47.110.90.170:19876
  app-id: 1551488520808730626
  app-key: 443b068f8b384e54b8eef73d6bad5414gyh2djnMD5wDB3bmLa
  app-secret: 696c57eeca1741119b03385799fc1a4219DCAA1DB87661E9A3BCD27A05C0403A60717DFF7137C319BC183C3A9C438A4C

datacenter:
  neikong:
    address: http://localhost:8303

app:
  auth:
    dev: false


#dubbo:
#  application:
#    logger: slf4j
#    name: ${spring.application.name}
#  registry:
#    address: nacos://192.168.2.66:8848
#  consumer:
#    timeout: 6000

is:
  mock:
    user: false
    data: false
  interactive: false

#rocketmq:
#  name-server: 192.168.2.66:9876
#  producer:
#    group: admin-producer-grp # 生产者分组
#    send-message-timeout: 3000 # 发送消息超时时间，单位：毫秒。默认为 3000 。
#    compress-message-body-threshold: 4096 # 消息压缩阀值，当消息体的大小超过该阀值后，进行消息压缩。默认为 4 * 1024B
#    max-message-size: 4194304 # 消息体的最大允许大小。。默认为 4 * 1024 * 1024B
#    retry-times-when-send-failed: 2 # 同步发送消息时，失败重试次数。默认为 2 次。
#    retry-times-when-send-async-failed: 2 # 异步发送消息时，失败重试次数。默认为 2 次。
#    retry-next-server: false # 发送消息给 Broker 时，如果发送失败，是否重试另外一台 Broker 。默认为 false
#    access-key: # Access Key ，可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/acl/user_guide.md 文档
#    secret-key: # Secret Key
#    enable-msg-trace: true # 是否开启消息轨迹功能。默认为 true 开启。可阅读 https://github.com/apache/rocketmq/blob/master/docs/cn/msg_trace/user_guide.md 文档
#    customized-trace-topic: RMQ_SYS_TRACE_TOPIC # 自定义消息轨迹的 Topic 。默认为 RMQ_SYS_TRACE_TOPIC 。

## 密码加密密钥
deskey: 4MWlJTDESnw=
## 免登录
avoid:
  ## 密钥
  login-key: 123
  ## 有效期/h，0或空=无限制
  login-time: 1
token:
  ## 有效期/h
  expire-time: 8
  ## 密钥
  secret: e1a39cc345b94d3b88f3e07f332009ad
